server:
  port: 10004

spring:
  application:
    name: wbiao-web-order
  thymeleaf:
    cache: false
  redis:
    host: 192.168.134.66
    port: 6379
    password:
    database: 0 #Redis数据库索引（默认为0）
    timeout: 3000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8   #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

  instance: #服务名称的修改
    instance-id: wbiao-web-order
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: wbiao-web-order
  company.name: www.wbiao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  build.description: ${project.description}

feign:
  hystrix:
    enabled: true
#hystrix超时时间配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000