server:
  port: 8001

spring:
  application:
    name: wbiao-goods
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/wbiao?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

  instance: #服务名称的修改
    instance-id: wibao-server-goods
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: wbiao-goods
  company.name: www.wbiao.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  build.description: ${project.description}

mybatis: #别名
  type-aliases-package: com.wbiao.goods.pojo

workerId: 0
datacenterId: 0




